Release pipeline

diff --git a/azure-pipelines-release.yml b/azure-pipelines-release.yml
--- a/azure-pipelines-release.yml
+++ b/azure-pipelines-release.yml
@@ -2,54 +2,54 @@ trigger: none
 pr: none
 
 pool:
-  vmImage: 'ubuntu-latest'
+  vmImage: "ubuntu-latest"
 
 steps:
-- checkout: self
-- task: InstallSSHKey@0
-  inputs:
-    knownHostsEntry: '$(KNOWN_HOST)' 
-    sshPublicKey: '$(SSH_PUBLIC_KEY)'
-    sshKeySecureFile: 'azure-pipelines-ssh-key-new'
-- task: DockerInstaller@0
-  inputs:
-    dockerVersion: '17.09.0-ce'
-- task: Docker@2
-  displayName: Login to ACR
-  inputs:
-    containerRegistry: 'ecpacr'
-    command: 'login'
-- task: Docker@2
-  displayName: Login to ACR
-  inputs:
-    command: login
-    containerRegistry: mocimages-connection
-- task: GoTool@0
-  inputs:
-    version: '1.15.x'
+  - checkout: self
+  - task: InstallSSHKey@0
+    inputs:
+      knownHostsEntry: "$(KNOWN_HOST)"
+      sshPublicKey: "$(SSH_PUBLIC_KEY)"
+      sshKeySecureFile: "azure-pipelines-ssh-key-new"
+  - task: DockerInstaller@0
+    inputs:
+      dockerVersion: "17.09.0-ce"
+  - task: Docker@2
+    displayName: Login to ACR
+    inputs:
+      containerRegistry: "ecpacr"
+      command: "login"
+  - task: Docker@2
+    displayName: Login to ACR
+    inputs:
+      command: login
+      containerRegistry: mocimages-connection
+  - task: GoTool@0
+    inputs:
+      version: "1.17.x"
 
-- script: |
-    git config --global url.ssh://git@github.com/.insteadOf https://github.com/
-    chmod +x hack/ensure-kustomize.sh
-    chmod +x hack/gen-flavors.sh
-    chmod +x hack/for-pipeline.sh
-    hack/ensure-kustomize.sh
-    hack/for-pipeline.sh
-    GOPATH_BIN="$(go env GOPATH)/bin/"
-    PATH=$GOPATH_BIN:$PATH
+  - script: |
+      git config --global url.ssh://git@github.com/.insteadOf https://github.com/
+      chmod +x hack/ensure-kustomize.sh
+      chmod +x hack/gen-flavors.sh
+      chmod +x hack/for-pipeline.sh
+      hack/ensure-kustomize.sh
+      hack/for-pipeline.sh
+      GOPATH_BIN="$(go env GOPATH)/bin/"
+      PATH=$GOPATH_BIN:$PATH
 
-    if [[ -z "${RELEASE_TAG}" ]]; then
-      echo "ERROR: variable RELEASE_TAG is required. This is the RELEASE pipeline, not the ci pipeline. if you are triggering this for CI you are in the wrong place."
-      exit 1
-    fi
+      if [[ -z "${RELEASE_TAG}" ]]; then
+        echo "ERROR: variable RELEASE_TAG is required. This is the RELEASE pipeline, not the ci pipeline. if you are triggering this for CI you are in the wrong place."
+        exit 1
+      fi
 
-    make REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) docker-build docker-push
-    make REGISTRY=mocimages.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) docker-build docker-push
-    make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) release
-    make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) generate-flavors
-    make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) release-pipelines
-  workingDirectory: '$(System.DefaultWorkingDirectory)'
-  displayName: 'Build CAPH'
+      make REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) docker-build docker-push
+      make REGISTRY=mocimages.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) docker-build docker-push
+      make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) release
+      make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) generate-flavors
+      make PROD_REGISTRY=ecpacr.azurecr.io IMAGE_NAME=caphcontroller TAG=$(RELEASE_TAG) release-pipelines
+    workingDirectory: "$(System.DefaultWorkingDirectory)"
+    displayName: "Build CAPH"
 
-- publish: $(System.DefaultWorkingDirectory)/out
-  artifact: releases
+  - publish: $(System.DefaultWorkingDirectory)/out
+    artifact: releases
